file_format: "1"
id: lily58-v2
name: Lily58-v2
type: shield
url: https://github.com/kata0510/Lily58
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - lily58-v2_left
  - lily58-v2_right